import Head from "next/head";
import Header from "../components/header";

export default function format({ children, searchtext, setsearchtext }) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta charset="utf-8" />
      </Head>

      <Header searchtext={searchtext} setsearchtext={setsearchtext}></Header>
      <main>{children}</main>
    </>
  );
}
